# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf8d3d5a504f61bfe5746ed055696166d869f478bdf58fc6f9c2fae3cf3902e0f6a8543d5ec4c970581b8bf9bf655aca391524fab437489d59a6e7e71f4710b

test:
  secret_key_base: b08d96b781bb74464f7cce546910762484245725246033032969615f92e9e7ceb111dbff5d47efa8e61fcebdea6a8f0821cdbdeafadb03786a74565c00f2fefa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
